baseURL = "https://www.katiehunterwriter.com/"
languageCode = "en-us"
pagination.pagerSize = 6
summarylength = 10
title = "Katie Hunter"
theme = "coHubloggeb"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "Writing"
    url= "writing"
    weight= 2
  [[menu.main]]
    name = "Testimonials"
    url= "testimonials"
    weight= 3
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 4
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 5

[params]
  summarylength = 80
  logo = "images/logo.png"
  author = "Katie Hunter"
  authorThumb = "images/author.png"
  #authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
  #authorPhone = "+33-257634 534"
  #instaUsername = "mary_astor"
  #facebookUsername = "mary_astor"
  twitterUsername = "kahunteroma"
  #linkedinUsername = "mary_astor"
  #blogTitle = "Articles"
  #blogSubTitle = "View the latest news on Blogger"
  #trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeURL  = "mbjelwrz"
  #googleMapAPI = ""

[taxonomies]
  tag = "tags"
